### ISSUE TITLE
how to toggle settings from other extension 

### ISSUE THREAD

**Issue by KnIfER** [z0al/settings-toggle#158] opened 2022-01-17 10:59 UTC
I want to add a status bar button to toggle wrapTabs . But it only invokes the toggle panel, not toggle the settings.

```
var right=0;
            var e=vscode_1.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
            e.text = '$(extensions-view-icon)';
            e.tooltip = 'Toggle Wrap Tabs';
            e.command = {
                    "title": "wrap",
                    "command": "settings-toggle.toggle-workspace",
                    "arguments": ["workbench.editor.wrapTabs"]
                    ,"args": {
                        "action": "toggle",
                        "setting": "workbench.editor.wrapTabs"
                      }
                };
            e.color = 'yellow';
            e.show();
```

**Comment by z0al** [comment] 2022-01-17 11:53
The extension doesn't yet read `args` command param. 

Duplicate of https://github.com/z0al/settings-toggle/issues/58

**Closed** 2022-01-17 11:54 UTC
